#### **IMPORTANDO LIBRERÍA NUMPY**

In [1]:
import numpy as np

##### Creando una lista de 10 Elementos

In [2]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

##### Transformando la Lista a un Array

In [3]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Corroborando el tipo de estructura


In [4]:
type(arreglo)

numpy.ndarray

##### Corroborando el tipo de datos del arreglo


In [5]:
arreglo.dtype

dtype('int64')

##### Definiendo el Array de int32 a float32


In [6]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### Sigue siendo un array de int32


In [7]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Transformando los datos de int32 a float32


In [8]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### También existe una función similar a Range pero ocupando Arrays

In [9]:
arreglonuevo = np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Arreglo de 2 en 2 utilizando Arange

In [10]:
arreglonuevo2 = np.arange(1,11,2)
arreglonuevo2

array([1, 3, 5, 7, 9])

<h4 style = "color:lightblue"><b>ALGUNAS FUNCIONES DE NUMPY</b></h4>
<h4 style = "color:aquamarine">Obteniendo el promedio del array</h3>


In [11]:
promedio = np.mean(arreglo)
promedio

np.float64(5.5)

<h4 style = "color:aquamarine">Obteniendo la mediana del array</h4>


In [12]:
mediana = np.median(arreglo)
mediana

np.float64(5.5)

<h4 style = "color:aquamarine"> Desviación Estandar del Arreglo </h4>


In [13]:
desviacion_std = np.std(arreglo)
desviacion_std

np.float64(2.8722813232690143)

<h4 style = "color:aquamarine"> Generación de un arreglo de 10 elementos de solo unos </h4>

In [14]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

<h4 style = "color:aquamarine"> Generación de un arreglo de 10 elementos de solo ceros </h4>

In [15]:
arreglo_de_ceros = np.zeros(5)
arreglo_de_ceros

array([0., 0., 0., 0., 0.])

<h4 style = "color:aquamarine"> Transformando el arreglo de unos de punto flotante a enteros </h4>


In [16]:
arreglo_int_ones = arreglo_de_unos.astype(int)
arreglo_int_ones 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

<h3 style = "color:orange"> <b>UTILIZANDO LA FUNCIÓN RANDOM</b> </h4>
<h4 style = "color:yellow"> Generando arreglo aleatorio de 5 elementos de Número entre 0 y 1</h4>



In [17]:
arreglo_aleatorio = np.random.rand(10)
arreglo_aleatorio 

array([0.30663221, 0.6859473 , 0.11314965, 0.76277406, 0.74876147,
       0.55803875, 0.13195439, 0.62371289, 0.9699612 , 0.60156048])

<h4 style = "color:yellow"> Generando una matriz aleatoria de 3x3</h4>


In [18]:
matriz = np.random.rand(3,3)
matriz

array([[0.46672364, 0.80259656, 0.2085144 ],
       [0.2360438 , 0.08719483, 0.96866367],
       [0.78045071, 0.73243871, 0.05805525]])

<h4 style = "color:yellow"> Generando un arreglo aleatorio de 10 números enteros del 1 al 5</h4>


In [19]:
arreglo_aleatorio2  = np.random.randint(1,1001,10)
arreglo_aleatorio2

array([905, 178, 712, 507, 510, 935, 293,  14, 727, 459], dtype=int32)

<h4 style = "color:yellow"> Generando una matriz aleatoria de 10 números enteros del 1 al 100</h4>


In [20]:
matriz2 = np.random.randint(1,101,(10,10))
matriz2

array([[29, 14, 83, 29, 17, 28,  3, 31, 50, 51],
       [61, 73, 90, 75, 81, 61, 29, 45, 73, 82],
       [56,  5, 24, 17, 81, 62, 21, 16, 59, 40],
       [53,  3, 83, 83, 20, 87, 90, 92, 74, 89],
       [53, 34, 22,  5, 83, 49, 56, 94, 65, 40],
       [13, 74, 26,  4, 94,  4, 92, 70, 48, 20],
       [34, 85, 75, 71, 96, 53, 79, 50, 56, 45],
       [26, 74, 79, 26, 23, 32, 24, 27, 72, 82],
       [46, 35, 83, 99, 75, 52, 23, 59, 34,  7],
       [19, 48, 35, 52, 60, 49, 35, 19, 96, 93]], dtype=int32)